# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/adrien/git-repo/GraphXair/Doc/groupeAdd.ui'
#
# Created: Thu Apr 16 13:59:26 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(916, 535)
        self.gridLayout_9 = QtWidgets.QGridLayout(Form)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelGroupe = QtWidgets.QLabel(Form)
        self.labelGroupe.setObjectName("labelGroupe")
        self.gridLayout_5.addWidget(self.labelGroupe, 0, 0, 1, 1)
        self.listViewGroupe = QtWidgets.QListView(Form)
        self.listViewGroupe.setEnabled(True)
        self.listViewGroupe.setMinimumSize(QtCore.QSize(0, 350))
        self.listViewGroupe.setObjectName("listViewGroupe")
        self.gridLayout_5.addWidget(self.listViewGroupe, 1, 0, 1, 1)
        self.checkBoxGroupe = QtWidgets.QCheckBox(Form)
        self.checkBoxGroupe.setObjectName("checkBoxGroupe")
        self.gridLayout_5.addWidget(self.checkBoxGroupe, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelNom = QtWidgets.QLabel(Form)
        self.labelNom.setObjectName("labelNom")
        self.gridLayout_4.addWidget(self.labelNom, 0, 0, 1, 1)
        self.lineEditNom = QtWidgets.QLineEdit(Form)
        self.lineEditNom.setReadOnly(True)
        self.lineEditNom.setObjectName("lineEditNom")
        self.gridLayout_4.addWidget(self.lineEditNom, 1, 0, 1, 1)
        self.checkBoxNom = QtWidgets.QCheckBox(Form)
        self.checkBoxNom.setObjectName("checkBoxNom")
        self.gridLayout_4.addWidget(self.checkBoxNom, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelStations = QtWidgets.QLabel(Form)
        self.labelStations.setObjectName("labelStations")
        self.gridLayout.addWidget(self.labelStations, 0, 0, 1, 1)
        self.listViewStations = QtWidgets.QListView(Form)
        self.listViewStations.setMinimumSize(QtCore.QSize(0, 400))
        self.listViewStations.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listViewStations.setObjectName("listViewStations")
        self.gridLayout.addWidget(self.listViewStations, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelParametre = QtWidgets.QLabel(Form)
        self.labelParametre.setObjectName("labelParametre")
        self.gridLayout_2.addWidget(self.labelParametre, 0, 0, 1, 1)
        self.listViewParametres = QtWidgets.QListView(Form)
        self.listViewParametres.setMinimumSize(QtCore.QSize(0, 400))
        self.listViewParametres.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listViewParametres.setObjectName("listViewParametres")
        self.gridLayout_2.addWidget(self.listViewParametres, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 2, 1, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 4, 1, 1, 1)
        self.buttonCreer = QtWidgets.QPushButton(Form)
        self.buttonCreer.setObjectName("buttonCreer")
        self.gridLayout_8.addWidget(self.buttonCreer, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Création Groupe"))
        self.labelGroupe.setText(_translate("Form", "Groupe"))
        self.checkBoxGroupe.setText(_translate("Form", "Valider"))
        self.labelNom.setText(_translate("Form", "Nom"))
        self.checkBoxNom.setText(_translate("Form", "Valider"))
        self.labelStations.setText(_translate("Form", "Stations"))
        self.labelParametre.setText(_translate("Form", "Paramètres"))
        self.buttonCreer.setText(_translate("Form", "Créer groupe"))


