# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/adrien/mainwindow.ui'
#
# Created: Wed Apr 15 15:57:59 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1452, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tabFenPrinc = QtWidgets.QTabWidget(self.centralwidget)
        self.tabFenPrinc.setStyleSheet("")
        self.tabFenPrinc.setObjectName("tabFenPrinc")
        self.tabGraph = QtWidgets.QWidget()
        self.tabGraph.setStyleSheet("")
        self.tabGraph.setObjectName("tabGraph")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tabGraph)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonSupprGroupe = QtWidgets.QPushButton(self.tabGraph)
        self.buttonSupprGroupe.setObjectName("buttonSupprGroupe")
        self.gridLayout.addWidget(self.buttonSupprGroupe, 1, 1, 1, 1)
        self.buttonAjoutGroupe = QtWidgets.QPushButton(self.tabGraph)
        self.buttonAjoutGroupe.setObjectName("buttonAjoutGroupe")
        self.gridLayout.addWidget(self.buttonAjoutGroupe, 0, 1, 1, 1)
        self.treeViewGroupe = QtWidgets.QTreeView(self.tabGraph)
        self.treeViewGroupe.setMinimumSize(QtCore.QSize(500, 150))
        self.treeViewGroupe.setObjectName("treeViewGroupe")
        self.gridLayout.addWidget(self.treeViewGroupe, 0, 0, 2, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonZoomP = QtWidgets.QPushButton(self.tabGraph)
        self.buttonZoomP.setMaximumSize(QtCore.QSize(85, 30))
        self.buttonZoomP.setObjectName("buttonZoomP")
        self.gridLayout_2.addWidget(self.buttonZoomP, 0, 0, 1, 1)
        self.buttonZoomM = QtWidgets.QPushButton(self.tabGraph)
        self.buttonZoomM.setMaximumSize(QtCore.QSize(85, 30))
        self.buttonZoomM.setObjectName("buttonZoomM")
        self.gridLayout_2.addWidget(self.buttonZoomM, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 1, 2, 2)
        spacerItem2 = QtWidgets.QSpacerItem(199, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 0, 3, 1, 1)
        self.buttonLegende = QtWidgets.QPushButton(self.tabGraph)
        self.buttonLegende.setObjectName("buttonLegende")
        self.gridLayout_10.addWidget(self.buttonLegende, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelTabStations = QtWidgets.QLabel(self.tabGraph)
        self.labelTabStations.setObjectName("labelTabStations")
        self.gridLayout_5.addWidget(self.labelTabStations, 0, 0, 1, 1)
        self.listViewStations = QtWidgets.QListView(self.tabGraph)
        self.listViewStations.setMinimumSize(QtCore.QSize(200, 350))
        self.listViewStations.setMaximumSize(QtCore.QSize(200, 700))
        self.listViewStations.setStyleSheet("")
        self.listViewStations.setObjectName("listViewStations")
        self.gridLayout_5.addWidget(self.listViewStations, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 2, 1, 2, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem7, 2, 1, 1, 1)
        self.frameGraph = QtWidgets.QFrame(self.tabGraph)
        self.frameGraph.setMinimumSize(QtCore.QSize(800, 400))
        self.frameGraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraph.setObjectName("frameGraph")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frameGraph)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.graphView = QtWidgets.QGraphicsView(self.frameGraph)
        self.graphView.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.graphView.setObjectName("graphView")
        self.gridLayout_12.addWidget(self.graphView, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frameGraph, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 2, 2, 2, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelTabParametre = QtWidgets.QLabel(self.tabGraph)
        self.labelTabParametre.setObjectName("labelTabParametre")
        self.gridLayout_4.addWidget(self.labelTabParametre, 0, 0, 1, 1)
        self.listViewParametre = QtWidgets.QListView(self.tabGraph)
        self.listViewParametre.setMinimumSize(QtCore.QSize(200, 350))
        self.listViewParametre.setMaximumSize(QtCore.QSize(200, 700))
        self.listViewParametre.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.listViewParametre.setObjectName("listViewParametre")
        self.gridLayout_4.addWidget(self.listViewParametre, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 2, 3, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 3, 4, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelDate = QtWidgets.QLabel(self.tabGraph)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout_6.addWidget(self.labelDate, 0, 0, 1, 1)
        self.dateTimeDate = QtWidgets.QDateTimeEdit(self.tabGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeDate.sizePolicy().hasHeightForWidth())
        self.dateTimeDate.setSizePolicy(sizePolicy)
        self.dateTimeDate.setMinimumSize(QtCore.QSize(200, 0))
        self.dateTimeDate.setReadOnly(True)
        self.dateTimeDate.setObjectName("dateTimeDate")
        self.gridLayout_6.addWidget(self.dateTimeDate, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelTaux = QtWidgets.QLabel(self.tabGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTaux.sizePolicy().hasHeightForWidth())
        self.labelTaux.setSizePolicy(sizePolicy)
        self.labelTaux.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelTaux.setObjectName("labelTaux")
        self.gridLayout_7.addWidget(self.labelTaux, 0, 0, 1, 1)
        self.lineEditTaux = QtWidgets.QLineEdit(self.tabGraph)
        self.lineEditTaux.setReadOnly(True)
        self.lineEditTaux.setObjectName("lineEditTaux")
        self.gridLayout_7.addWidget(self.lineEditTaux, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 4, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(891, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem10, 5, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabFenPrinc.addTab(self.tabGraph, "")
        self.tabValidation = QtWidgets.QWidget()
        self.tabValidation.setObjectName("tabValidation")
        self.tabFenPrinc.addTab(self.tabValidation, "")
        self.gridLayout_11.addWidget(self.tabFenPrinc, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1452, 27))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionFermer = QtWidgets.QAction(MainWindow)
        self.actionFermer.setObjectName("actionFermer")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionFermer)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindow)
        self.tabFenPrinc.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GraphXair"))
        self.buttonSupprGroupe.setText(_translate("MainWindow", "Supprimer Groupe"))
        self.buttonAjoutGroupe.setText(_translate("MainWindow", "Ajouter Groupe"))
        self.buttonZoomP.setText(_translate("MainWindow", "Zoom +"))
        self.buttonZoomM.setText(_translate("MainWindow", "Zoom -"))
        self.buttonLegende.setText(_translate("MainWindow", "Légende"))
        self.labelTabStations.setText(_translate("MainWindow", "Stations"))
        self.labelTabParametre.setText(_translate("MainWindow", "Paramètres"))
        self.labelDate.setText(_translate("MainWindow", "Date"))
        self.dateTimeDate.setDisplayFormat(_translate("MainWindow", "yyyy-mm-dd hh:mm:ss"))
        self.labelTaux.setText(_translate("MainWindow", "Taux"))
        self.tabFenPrinc.setTabText(self.tabFenPrinc.indexOf(self.tabGraph), _translate("MainWindow", "Graphique"))
        self.tabFenPrinc.setTabText(self.tabFenPrinc.indexOf(self.tabValidation), _translate("MainWindow", "Validation"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionFermer.setText(_translate("MainWindow", "Fermer"))
